"""Application boundaries for planning and worker infrastructure."""

from collections.abc import AsyncIterator
from typing import Protocol

from universal_agent_runtime.domain.orchestration import ExecutionGraph, UserTask, WorkerSpec, WorkerStatus


class Coordinator(Protocol):
    def plan(self, task: UserTask) -> ExecutionGraph: ...


class WorkerOrchestrator(Protocol):
    async def submit(self, worker: WorkerSpec) -> WorkerStatus: ...
    async def status(self, worker_id: str) -> WorkerStatus: ...
    def watch(self, worker_id: str) -> AsyncIterator[WorkerStatus]: ...
    async def suspend(self, worker_id: str) -> WorkerStatus: ...
    async def resume(self, worker_id: str) -> WorkerStatus: ...
    async def delete(self, worker_id: str) -> None: ...
